### ISSUE TITLE
Fix for issue #100 slows down gedcom parsing by a factor of 4

### ISSUE THREAD

**Issue by haralduna** [frizbog/gedcom4j#101]
With gedcom4j version 2.2.6 reading my example file with 2306 persons without any faulty line breaks takes 60 seconds with Android emulator connected. I have made a patch without regexp and the same operation now takes 15 seconds.

The patch is enclosed.

[0001-removed-greedy-regexp.txt](https://github.com/frizbog/gedcom4j/files/279205/0001-removed-greedy-regexp.txt)

**Comment by frizbog** [comment]
Excellent point and thanks for reporting this. I honestly haven't paid much attention to performance.

The latest code checked in to 2.2.7-SNAPSHOT took care of a number of inefficient things in the parser and supporting classes, and I got the parser loading a 700k gedcom in roughly 10% of the runtime required by 2.2.6 in my testing.

**Comment by haralduna** [comment]
I have tried your 2.2.7-SNAPSHOT, I repeated the test, and now the same GEDCOM file parsing takes 3 seconds (!). This is great. Thank you. Compared to 2.2.6 this is 20 times faster.

**Comment by frizbog** [comment]
Released in v2.2.7
