### ISSUE TITLE
Parsing lines with level > 9

### ISSUE THREAD

**Issue by dszqqjf** [frizbog/gedcom4j#102]
I was just reading through some of the source (great work!) and noticed a minor potential issue and thought I'd at least document it.  It doesn't appear that the constructor for org.gedcom4j.parser.LinePieces will properly handle lines where the level is two digits.  I'd earlier noticed that the spec says "Level numbers must be between 0 to 99..." so I'm thinking it should technically be possible for the level to be greater than nine (ref pg 10 of the 5.5.1 draft standard).

**Comment by frizbog** [comment]
Good catch. Technically possible (though unlikely), so I will fix this. Thanks for reporting it!

**Comment by frizbog** [comment]
Fixed in v2.2.8-SNAPSHOT

**Comment by dszqqjf** [comment]
Count me as a fan - thanks Matt!

**Comment by frizbog** [comment]
:-D

This email just made my day.  Cheers!

M

**Comment by frizbog** [comment]
Released in v2.2.8.
