### ISSUE TITLE
Function to cancel ongoing operation

### ISSUE THREAD

**Issue by haralduna** [frizbog/gedcom4j#105]
The parsing operation can take a long time for bigger GEDCOM files. The user can pause or exit the application while the GEDCOM file is being parsed, and it is no good idea to let the parsing continue after application stop, especially when the resource usage is pretty high on both memory and processing. A thread cannot be aborted forcefully in Java, so I need a way to tell the parser to end its operation.

This can be done by introducing a flag in the various loops in the parser, or alternatively, introduce something into the stream or list that will lead to termination.

**Comment by frizbog** [comment]
Also useful would be a way to register listeners for notifications about progress, so feedback can be given to uses.

**Comment by haralduna** [comment]
Yes, that is a very useful addition.

**Comment by frizbog** [comment]
v2.3.0-SNAPSHOT of 2016-06-28T22:06:30-04:00 provides this capability, but please note that there have been a few changes to the API (mostly package changes).

The changes to the API are as follows:
- Exceptions defined in gedcom4j are now all in the org.gedcom4j.exception package, and these are checked exceptions, so you'll probably need to touch up your imports.
- The GedcomParser now has new methods for registering and unregistering listeners for file read progress and data parsing progress, and to set how frequently your listeners are notified. You can also cancel a load/parse operation in progress using the GedcomParser.cancel() method.
- The GedcomWriter now has new methods for registering and unregistering listeners for progress updates on constructing string data from GEDCOM data, and for writing the files, and to set how frequently your listeners are notified. You can also cancel a construct/write operation in progress using the GedcomWriter.cancel() method.
- Several classes were moved to new packages, including some enumerations you might be using (like Encoding) so again, you may need to touch up your imports.
- Visibility of some classes has also changed (such as the Tag enum), so you may no longer be able to use them.

**Comment by frizbog** [comment]
Released in v.2.30
