### ISSUE TITLE
StringTreeBuilder would be improved if it didn't need to hold an entire copy of the file in memory

### ISSUE THREAD

**Issue by frizbog** [frizbog/gedcom4j#106]
The makeStringTreeFromFlatLines() method of StringTreeBuilder take as a parameter a List<String> containing all the lines of the file being read.  This consumes a lot of memory unnecessarily (at least temporarily) while the file is parsed. If GedcomFileParser could support returning a BufferedReader object (in addition to getting the full list of file lines as Strings) that would return a line of the file at a time, StringTreeBuilder could be modified to use that reader and only a line at a time would need to be in temporary memory instead of the entire file's contents....which would make a huge difference in heap consumption, obviously.

**Comment by frizbog** [comment]
v2.3.1-SNAPSHOT at 2016-07-03T12:12:33-04:00 includes this code.

**Comment by haralduna** [comment]
Thank you, I tried your latest version 6d73abd and it works very well.
I am attaching two diagrams showing memory usage over time while reading my 8000 person file. One showing the clean 2.3.0 and one showing your latest 2.3.1-SNAPSHOT. The steeper curve is the parsing part. The last smooth slowly increase curve is my post processing. The operation takes about 8 second longer on your latest version (I am not sure that is a big issue, avoiding peek allocation is more important.)

![2 3 0-clean](https://cloud.githubusercontent.com/assets/11294027/16559926/8e53c908-41f0-11e6-9441-71d9557fef6c.png)
![2 3 1-snapshot-6d73abd](https://cloud.githubusercontent.com/assets/11294027/16559927/8e55488c-41f0-11e6-9dc7-c9cc7c7c7673.png)

**Comment by frizbog** [comment]
Harald - thanks so much for the confirmation and the excellent graphs!

**Comment by haralduna** [comment]
Found a little flaw in the parser rate handling. A patch is attached.

[0001-fixed-parser-progress-rate.patch.txt](https://github.com/frizbog/gedcom4j/files/350450/0001-fixed-parser-progress-rate.patch.txt)

**Comment by haralduna** [comment]
Same patch with fixed test cases.
[0001-fixed-parser-progress-rate.patch.txt](https://github.com/frizbog/gedcom4j/files/351660/0001-fixed-parser-progress-rate.patch.txt)

**Comment by frizbog** [comment]
Released in v2.3.1
