### ISSUE TITLE
Cannot import GEDCOM from GENi due to leading blanks

### ISSUE THREAD

**Issue by haralduna** [frizbog/gedcom4j#166]
I just learned from a user that GEDCOM exports from GENi contain leading blanks (for readability) and that gedcom4j fails to import such lines.

From the GEDCOM 5.5 standard:
_Leading white space (tabs, spaces, and extra line terminators) preceding a GEDCOM line should be ignored by the reading system. Systems generating GEDCOM should not place any white space in front of the GEDCOM line._

I am attaching a simple GEDCOM export from GENi demonstrating the issue.
[geni-test.txt](https://github.com/frizbog/gedcom4j/files/500106/geni-test.txt)

I think GENi is a pretty huge player in the market so it would be nice if import was working.

**Comment by frizbog** [comment]
Confirmed to be a problem with UTF8 encoded files. This had been addressed way earlier in issue #57 but that file used ANSEL encoding.

**Comment by frizbog** [comment]
Fixed in 3.2.2-SNAPSHOT of 2016-09-29T08:04:22-04:00
Fixed in 4.0.0-SNAPSHOT of 2016-09-29T08:07:37-04:00

**Comment by frizbog** [comment]
Released in v3.2.2
