### ISSUE TITLE
Not able to get relations

### ISSUE THREAD

**Issue by unnivm** [frizbog/gedcom4j#187]
Hi,

I was able to parse my GEDCOM file and it has got 50000 individuals. I am not able to find any relationship among them though there are some relations between them,

Also, is it possible to get all the relations between two individuals? If so, how efficient will be the search mechanism?

thanks

**Comment by frizbog** [comment]
Please see the KinshipNameCalculator class (http://gedcom4j.org/javadoc/org/gedcom4j/relationship/KinshipNameCalculator.html) as well as example code for using the RelationshipCalculator as documented at http://gedcom4j.org/main/example-calculating-relationships
