### ISSUE TITLE
Loading problem with large Family Historian 6.2.6 file

### ISSUE THREAD

**Issue by gjwo** [frizbog/gedcom4j#195]
I have been testing quite happily with an older (and smaller 78221 lines ) .ged file from Family Historian version 3.1 this file loads but there are errors and warnings which I display after loading.

 I recently tried to load the current .ged file which is much bigger (345645 lines) from Family Historian 6.2.6, but something is very wrong!

gedparser.load(...) returns OK, there are no errors or warnings (which is suspicious), but the data structure does not contain the people which would display OK from the earlier file, or in fact any people.
Any ideas on how I can resolve this, or collect relevant information to help?

**Comment by frizbog** [comment]
I'd need to try loading the file and seeing what I see.  Would you email it please to matt@gedcom4j.org and I will see what I can figure out?

**Comment by gjwo** [comment]
In GedcomParser load(filename) it looks like the streams open OK.
in load (bis) initialisation is OK but the first line appears to be null so no parsing!
my guess is there was a suppressed exception when opening the streams. I will email a screenshot

**Comment by gjwo** [comment]
Looks like it was a character set problem the file. It was encoded in USC2-BOM with a CHAR tag of UNICODE both have now been changed to UTF-8 and it all loads OK . The header is as below now: 
```
0 HEAD
1 SOUR FAMILY_HISTORIAN
2 VERS 6.2.6
2 NAME Family Historian
2 CORP Calico Pie Limited
1 FILE C:\Users\graha\Documents\Genealogy\FHData\Family Historian Projects\GJW Family Tree\GJW Family Tree.fh_data\GJW Family Tree.ged
1 GEDC
2 VERS 5.5
2 FORM LINEAGE-LINKED
1 CHAR UTF-8
1 DEST BROSKEEP (BROTHERS KEEPER)
1 _UID {59718A24-36B6-4564-979A-819A7B97353F}
1 _LIST Roots
2 _IDS I177,I1662,I1372,I466,I2750,I1649
1 _LIST UDF
2 _IDS F1,F6,F7,F8,F10,F12,F13,F31,F41,F65,F95,F99,F108,F109,F142,F147,F193,F198,F203,F204,F205,F206,F209,F210,F211,F212,F213,F214,F215,F216,F217,F218,F276,F282,F297,F478,F479,F564,F613,F634,F639,F656,F747,F748,I3,I6,I8,I11,I13,I21

```
