### ISSUE TITLE
First build of project after fresh git clone always fails

### ISSUE THREAD

**Issue by Nunnery** [frizbog/gedcom4j#70]
There are always two test failures during the first build of the project after a fresh git clone. These test failures are caused by a file not existing in the "tmp" directory.

Subsequent builds solve this issue on their own.

**Comment by frizbog** [comment]
Which tests? They should be updated to not assume the tmp folder exists.  

Matt

**Comment by Nunnery** [comment]
The tests that fail are in the GedcomWriter551Test class. Will update the specific classes to not assume file existence.

**Comment by Nunnery** [comment]
As a result of my commit 1c6b5d2efc5917a8cb0936479ea31b4e947affeb, the issue appears to be fixed both locally and on my Jenkins.

**Comment by Nunnery** [comment]
After testing a1b0039b44da214c5c1986d5cf71cac691fcd073, it appears to be fixed.
