### ISSUE TITLE
toString method is broken of class Individual

### ISSUE THREAD

**Issue by LarsTor** [frizbog/gedcom4j#88]
The variable "found" isn't resetted after usage in the birth block, but it's reused in the death block.

`        found = false;`
`         for (IndividualEvent d : getEventsOfType(IndividualEventType.DEATH)) `

**Comment by frizbog** [comment]
Fixed in 2.2.4-SNAPSHOT on 2015-02-05

**Comment by frizbog** [comment]
2.2.4 Released to Maven Central and on gedcom4j.org
