### ISSUE TITLE
Custom tags are not actually emitted in GedcomWriter emitCustomTags

### ISSUE THREAD

**Issue by dmitrychervov** [frizbog/gedcom4j#89]
Custom tags are written into a StringBuilder, but StringBuilder result is never used. Apparently, `lines.add(line.toString());` is missing.

**Comment by frizbog** [comment]
Well that's embarrassing.  Fixing now.

**Comment by frizbog** [comment]
Fixed in 2.2.4-SNAPSHOT build 83

**Comment by frizbog** [comment]
2.2.4 Released to Maven Central and on gedcom4j.org
