### ISSUE TITLE
Custom Tags for IndividualEvent are written twice in GedcomWriter

### ISSUE THREAD

**Issue by dmarks2** [frizbog/gedcom4j#95]
When loading a gedcom file which has custom tags for an event, those custom tags are written twice into the output.

Sample code:

```
GedcomParser gp = new GedcomParser();
gp.load(new BufferedInputStream(this.getClass().getResourceAsStream("/de/dm/test/handler/test.ged")));
GedcomWriter writer = new GedcomWriter(gp.gedcom);
writer.write(System.out);
```

Sample files ([sample.zip](https://github.com/frizbog/gedcom4j/files/219249/sample.zip))

* test.ged is the input file
* output.ged is the output

As you can see, the custom Tag "_ASSO" with "RELA" as child is being written twice into the output.

In the source code I see that "emitCustomTags" is being called twice:
* https://github.com/frizbog/gedcom4j/blob/master/src/main/java/org/gedcom4j/writer/GedcomWriter.java#L580
* https://github.com/frizbog/gedcom4j/blob/master/src/main/java/org/gedcom4j/writer/GedcomWriter.java#L750

**Comment by frizbog** [comment]
Fixed in latest 2.2.5-SNAPSHOT.

**Comment by dmarks2** [comment]
Thank you, it works.

**Comment by frizbog** [comment]
Release 2.2.5 to Maven Central.
